blank_issues_enabled: true
contact_links:
  - name: 讨论问题
    url: https://github.com/didi/KnowStreaming/discussions/new
    about: 发起问题、讨论 等等
  - name: KnowStreaming官网
    url: https://knowstreaming.com/
    about: KnowStreaming website
